trigger:
- main
 
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Build stage"
      displayName: "Build Start"
 
    - script: ls -la
      displayName: "List files"
 
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Deploy stage running"
      displayName: "Deploy Start"
 
                                           # ✅ required
 